### PR TITLE
FIX japanese

### PR DESCRIPTION
**Pull request by rikusen0335**
Thank you for making a great extension!
Well I made a fix for some weird Japanese, so I'm grad you review and merge my PR!

すばらしい拡張機能を作ってくれて、ありがとうございます！
すこし日本語のおかしいところがあったのを直したので、マージしていただけるとありがたいです！

### CODE REVIEW

**Comment by rikusen0335** [comment]
Can you merge this PR?

**Comment by littlegolden** [comment]
Sorry about the pmitting, just notice your pull, I will deal with this as soon as possible.

**Comment by qwexvf** [comment]
Nice! I also need asap!! thanks <3

**Comment by littlegolden** [comment]
@rikusen0335 Thank you so much, the new version has been released, please feel free to open any issue.

**Comment by rikusen0335** [comment]
Thank you for that. I really appreciate it.

**Pull request merged**
